apps:
 - name: prodcons
   period: 44
   executions: 200
   tasks:
    prod: 0
    cons: 1
 - name: dijkstra
   period: 41
   executions: 300
   tasks:
    dijkstra_0: 0
    dijkstra_1: 1
    dijkstra_2: 2
    dijkstra_3: 3
    dijkstra_4: 4
    print_dij: 5
    divider: 6
 - name: dtw
   period: 10
   executions: 200
   tasks:
    bank: 0
    p1: 1
    p2: 2
    p3: 3
    p4: 4
    recognizer: 5
 - name: pipeline_alpha
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
 - name: pipeline_beta
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
 - name: pipeline_gama
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
    pipe4: 4
    pipe5: 5
    pipe6: 6
    pipe7: 7
 - name: pipeline_alpha
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
 - name: prodcons
   period: 44
   executions: 200
   tasks:
    prod: 0
    cons: 1
 - name: dijkstra
   period: 41
   executions: 300
   tasks:
    dijkstra_0: 0
    dijkstra_1: 1
    dijkstra_2: 2
    dijkstra_3: 3
    dijkstra_4: 4
    print_dij: 5
    divider: 6
 - name: dtw
   period: 10
   executions: 200
   tasks:
    bank: 0
    p1: 1
    p2: 2
    p3: 3
    p4: 4
    recognizer: 5
 - name: pipeline_alpha
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
 - name: pipeline_beta
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
 - name: pipeline_gama
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3
    pipe4: 4
    pipe5: 5
    pipe6: 6
    pipe7: 7
 - name: pipeline_alpha
   period: 0
   executions: 200
   tasks:
    pipe0: 0
    pipe1: 1
    pipe2: 2
    pipe3: 3